package clinica_historias;

import clases.Paciente;
import clases.Usuario;
import clases.ConsultaMedica;
import estructuras.ListaConsultaMedica;
import java.util.Date;

public class JD_Atender extends javax.swing.JDialog {

    private Paciente paciente;
    private Usuario usuario;
    private ListaConsultaMedica listaConsultaMedica;
    private boolean consultaGuardada = false;

    public JD_Atender(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JD_Atender(java.awt.Frame parent, boolean modal, Paciente paciente, Usuario usuario, ListaConsultaMedica listaConsultaMedica) {
        super(parent, modal);
        this.paciente = paciente;
        this.usuario = usuario;
        this.listaConsultaMedica = listaConsultaMedica;
        initComponents();
        configurarDialog();
    }

    private void configurarDialog() {
        setTitle("Atender Paciente: " + paciente.getNombre() + " " + paciente.getApellidoPaterno());
        lblPaciente.setText("Paciente: " + paciente.getNombre() + " " + paciente.getApellidoPaterno() + " - " + paciente.getDni());
        setLocationRelativeTo(null);
    }

    public boolean isConsultaGuardada() {
        return consultaGuardada;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jta_diagnostico = new javax.swing.JTextArea();
        lbl7 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jta_tratamiento = new javax.swing.JTextArea();
        lblPaciente = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jta_diagnostico.setColumns(20);
        jta_diagnostico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jta_diagnostico.setRows(5);
        jScrollPane4.setViewportView(jta_diagnostico);

        lbl7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl7.setText("Diagnostico");

        lbl8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl8.setText("Tratamiento:");

        jta_tratamiento.setColumns(20);
        jta_tratamiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jta_tratamiento.setRows(5);
        jScrollPane3.setViewportView(jta_tratamiento);

        lblPaciente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPaciente.setText("lblPaciente");

        btnGuardar.setBackground(new java.awt.Color(27, 55, 79));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane4)
                        .addComponent(lbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                        .addComponent(lblPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblPaciente)
                .addGap(18, 18, 18)
                .addComponent(lbl7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lbl8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jta_diagnostico;
    private javax.swing.JTextArea jta_tratamiento;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lblPaciente;
    // End of variables declaration//GEN-END:variables

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String diagnostico = jta_diagnostico.getText().trim();
        String tratamiento = jta_tratamiento.getText().trim();
        Date fechaRegistro = new Date();

        if (diagnostico.isEmpty() || tratamiento.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe completar diagnóstico y tratamiento.");
            return;
        }

        if (usuario == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay usuario logueado.");
            return;
        }

        ConsultaMedica consulta = new ConsultaMedica(
                0, diagnostico, tratamiento, fechaRegistro, paciente, usuario, null
        );

        try {
            int idConsulta = listaConsultaMedica.guardarEnBD(consulta);
            if (idConsulta != -1) {
                consultaGuardada = true;
                javax.swing.JOptionPane.showMessageDialog(this, "Consulta médica guardada correctamente.");
                dispose(); // Cerrar el dialog
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar la consulta médica.");
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar la consulta: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose(); // Cerrar el dialog sin guardar
    }//GEN-LAST:event_btnCancelarActionPerformed
}
