package clinica_historias;

import conexion.Conexion;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class Login extends javax.swing.JFrame {

    private Conexion conexionDB;

    public Login(Conexion conexionDB) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.conexionDB = conexionDB;
        
        // default
        txtCorreo.setText("admin");
        txtContraseña.setText("1234");
        
        // Agregar listener para cerrar la conexión cuando se cierre la ventana
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                cerrarConexion();
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorIniciarSes = new javax.swing.JPanel();
        lblIniciarSes = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        txtContraseña = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenedorIniciarSes.setBackground(new java.awt.Color(255, 255, 255));

        lblIniciarSes.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblIniciarSes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIniciarSes.setText("Iniciar Sesion");
        lblIniciarSes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblContraseña.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblContraseña.setText("Contraseña:");

        lblCorreo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCorreo.setText("Correo:");

        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCorreo.setMargin(new java.awt.Insets(2, 10, 2, 10));

        btnLogin.setBackground(new java.awt.Color(51, 153, 255));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Ingresar");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        txtContraseña.setMargin(new java.awt.Insets(2, 10, 2, 10));

        javax.swing.GroupLayout contenedorIniciarSesLayout = new javax.swing.GroupLayout(contenedorIniciarSes);
        contenedorIniciarSes.setLayout(contenedorIniciarSesLayout);
        contenedorIniciarSesLayout.setHorizontalGroup(
            contenedorIniciarSesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorIniciarSesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedorIniciarSesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorIniciarSesLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(txtCorreo))
                    .addComponent(lblIniciarSes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(contenedorIniciarSesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(contenedorIniciarSesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtContraseña, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(contenedorIniciarSesLayout.createSequentialGroup()
                                .addGroup(contenedorIniciarSesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblContraseña)
                                    .addGroup(contenedorIniciarSesLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(lblCorreo)))
                                .addGap(0, 347, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        contenedorIniciarSesLayout.setVerticalGroup(
            contenedorIniciarSesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorIniciarSesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIniciarSes)
                .addGap(46, 46, 46)
                .addComponent(lblCorreo)
                .addGap(18, 18, 18)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblContraseña)
                .addGap(18, 18, 18)
                .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(contenedorIniciarSes, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 38, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String correo = txtCorreo.getText();
        String contraseña = txtContraseña.getText();
        
        if (correo.equals("admin") && contraseña.equals("1234")){
            Aplicacion app = new Aplicacion(conexionDB);
            app.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLoginActionPerformed
    
    /**
     * Método para cerrar la conexión de manera segura
     */
    private void cerrarConexion() {
        if (conexionDB != null) {
            conexionDB.cerrarConexion();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel contenedorIniciarSes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblIniciarSes;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
